#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a
# custom header (on web-01 and web-02)

sudo apt-get update
sudo apt-get -y install nginx

sudo chmod -R 755 /var/www
sed -i "47i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Hello World!" | tee /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo nginx -t
sudo service nginx restart
